env:
  global:
      - secure: Bj+BPOGhxYEdDRgD3FCpTMb5I7kOat5PZagbPXl/8Op4KQoU386sWf10GtQhQpAXJIcCbSZQPxiAB9cYw/LQOCN4HGHB8Uw3SSewPy6z4OBQ42I/BGiF+HypuIWy9pCj9qw3LLPnGeCHWBs7G3X+PnuJio6ROxEIGYnh9VVAFcM=
language: rust
install:
  - sudo apt-get install -qq libao-dev
after_script:
  - cargo doc
  - mv target/doc ./
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
